#!/usr/bin/env python3
# =====================================================================
# gen_t2f_model.py -- generate the digital-side model & calibration
# parameters from the analog characterization (analog/sim/results_tt.csv)
#
# Calibration: PIECEWISE-LINEAR over the measured breakpoints:
#   temp_half = T[i] + ((raw - C[i]) * GAIN[i]) >> 8
# Outputs:
#   scripts/t2f_model_params.py  : python dicts
#   tb/t2f_model_params.vh       : Verilog params (temp_engine + t2f model)
#
# Usage: python3 scripts/gen_t2f_model.py [--csv analog/sim/results_tt.csv]
# =====================================================================
import argparse
import csv
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default=str(ROOT / "analog/sim/results_tt.csv"))
    ap.add_argument("--gate-s", type=float, default=10e-3)
    args = ap.parse_args()

    rows = []
    with open(args.csv) as fh:
        for r in csv.DictReader(fh):
            try:
                t = float(r["temp_c"])
                fr = float(r["freq_hz"])
            except (ValueError, KeyError):
                continue
            if math.isfinite(fr):
                rows.append((t, fr))
    rows.sort()
    if len(rows) < 2:
        print("[ERROR] not enough valid points in", args.csv)
        sys.exit(1)

    print(f"[model] {len(rows)} valid f(T) points from {args.csv}")
    for t, fr in rows:
        print(f"        T={t:6.1f}C  f={fr/1e3:9.2f} kHz")

    gate = args.gate_s
    counts = [round(fr * gate) for _, fr in rows]
    temps  = [t for t, _ in rows]
    print(f"[calib] gate = {gate*1e3:g} ms")

    # ---- per-segment gains (Q8): GAIN[i] = (T[i+1]-T[i])*256/(C[i+1]-C[i])
    shift = 8
    gains = []
    for i in range(len(rows) - 1):
        dhalf = round((temps[i+1] - temps[i]) * 2.0)
        dcnt = counts[i+1] - counts[i]
        g = round(dhalf * (1 << shift) / dcnt) if dcnt > 0 else 1
        gains.append(max(1, g))

    # ---- expected readout error ----
    # error at the breakpoints is 0 by construction; estimate the
    # mid-segment error from the change of slope between adjacent segments
    n = len(rows)
    max_err = 0.0
    for i in range(1, n - 1):
        # slope mismatch between segment i-1 and segment i (in C per count)
        s0 = (temps[i] - temps[i-1]) / max(counts[i] - counts[i-1], 1)
        s1 = (temps[i+1] - temps[i]) / max(counts[i+1] - counts[i], 1)
        seg_len = counts[i+1] - counts[i-1]
        est = abs(s1 - s0) * seg_len / 8.0   # parabola mid-error bound
        max_err = max(max_err, est)
    print(f"  estimated worst-case piecewise-linear error: {max_err:.2f} C")

    # ---- linear fit for the behavioral T2F model (f in Hz) ----
    sx = sum(t for t, _ in rows)
    sy = sum(fr for _, fr in rows)
    sxx = sum(t * t for t, _ in rows)
    sxy = sum(t * fr for t, fr in rows)
    slope = (n * sxy - sx * sy) / (n * sxx - sx * sx)
    inter = (sy - slope * sx) / n
    print(f"  T2F model: f(T) = {slope:.2f}*T + {inter:.2f} Hz")

    # ---- pack Verilog parameters ----
    bp_cnt_pack = "".join(f"{c:04x}" for c in counts[::-1])  # LSB-first packed
    tpack = "".join(f"{int(t*100) & 0xFFFF:04x}" for t in temps[::-1])
    fpack = "".join(f"{int(fr) & 0xFFFFFFFF:08x}" for fr in reversed([fr for _, fr in rows]))
    bp_t_pack = "".join(f"{(int(t*2) & 0xFFFF):04x}" for t in temps[::-1])
    gain_pack = "".join(f"{g:03x}" for g in gains[::-1])
    nsec = len(rows)

    cal = {
        "gate_s": gate,
        "nsec": nsec,
        "bp_counts": counts,
        "bp_temps_c": temps,
        "gains": gains,
        "max_lin_err_c": max_err,
        "t2f_slope_hz_per_c": slope,
        "t2f_f0_hz": inter,
    }
    with open(ROOT / "scripts" / "t2f_model_params.py", "w") as f:
        f.write("# Auto-generated by scripts/gen_t2f_model.py -- do not edit\n")
        f.write(f"CAL = {cal!r}\n")

    vh = ROOT / "tb" / "t2f_model_params.vh"
    with open(vh, "w") as f:
        f.write("// Auto-generated by scripts/gen_t2f_model.py -- do not edit\n")
        f.write("`ifndef T2F_MODEL_PARAMS_VH\n")
        f.write("`define T2F_MODEL_PARAMS_VH\n")
        f.write(f"`define T2F_F0_HZ          {inter:.3f}\n")
        f.write(f"`define T2F_SLOPE_HZ_PER_C {slope:.3f}\n")
        f.write(f"`define T2F_NSEC           {nsec}\n")
        f.write(f"`define T2F_BP_CNT         288\'h{bp_cnt_pack}\n")
        f.write(f"`define T2F_BP_T           160\'h{bp_t_pack}\n")
        f.write(f"`define T2F_GAIN           108\'h{gain_pack}\n")
        f.write(f"`define T2F_T_PACK         {nsec*16}\'h{tpack}\n")
        f.write(f"`define T2F_F_PACK         {nsec*32}\'h{fpack}\n")
        f.write("`endif\n")
    print(f"  wrote {ROOT / 'scripts' / 't2f_model_params.py'}")
    print(f"  wrote {vh}")


if __name__ == "__main__":
    main()
