// Auto-generated by scripts/gen_t2f_model.py -- do not edit
`ifndef T2F_MODEL_PARAMS_VH
`define T2F_MODEL_PARAMS_VH
`define T2F_F0_HZ          577248.051
`define T2F_SLOPE_HZ_PER_C 1537.032
`define T2F_NSEC           10
`define T2F_BP_CNT         288'h1ddd1c7b1b571a421910185517e516a5155813ce
`define T2F_BP_T           160'h00fa00c800a000780050003600280000ffd8ffb0
`define T2F_GAIN           108'h02402302502102402002001f01a
`define T2F_T_PACK         160'h30d427101f4017700fa00a8c07d00000f830f060
`define T2F_F_PACK         320'h000baa59000b2036000aaddb000a41e00009ca15000981390009555e0008d88f0008565b0007bc75
`endif
