// =====================================================================
// tb_top.v -- full-chip test: T2F front-end model + measurement engine
// + I2C readout.  Verifies the reported temperature matches the model
// input within +/-1 LSB (0.5 C).
//
// Scenarios:
//   - T = 25.00 C  -> expect ~0x32 (25 C = 50 half-steps = 0x32)
//   - T = -40.00 C -> expect 0xD0 (two's complement: -80 = 0x1B0 -> 9-bit 0x1B0,
//                     MSB=0xD8? see: -40C in 0.5C units = -80; 9-bit two's
//                     complement of -80 = 512-80 = 432 = 0x1B0 -> MSB 0x1B? no:
//                     half = -80 -> binary(9) = 1_1011_0000 -> msb=0xD8? compute:
//                     -80 = 0x1B0 in 9 bits (512-80=432=0x1B0); msb=0x1B? wait
//                     432 = 0b1_1011_0000 -> 9 bits: 1_1011_0000 -> msb[8:1]=
//                     0b1101_1000=0xD8, lsb bit0=0.  But saturate to -110 so ok.
//   - T = 125.00 C -> expect 250 = 0xFA (0.5C units)
//
// SPDX-License-Identifier: Apache-2.0
// =====================================================================
`timescale 1ns/1ps
`include "t2f_model_params.vh"

module tb_top;

    reg        clk = 0;
    reg        rstn = 0;
    wire       scl, sda;
    pullup(scl);
    pullup(sda);
    wire       os_int;
    pullup(os_int);
    reg  [31:0] temp_x100 = 2500;   // 25.00 C
    reg        t2f_in;

    always #50 clk = ~clk;          // 10 MHz

    // ---- DUT ----
    temp_sensor_top #(
        .I2C_ADDR    (7'h48),
        .GATE_CYCLES (32'd100000),  // 10 ms @ 10 MHz
        .NSEC        (`T2F_NSEC),
        .BP_CNT      (`T2F_BP_CNT),
        .BP_T        (`T2F_BP_T),
        .GAIN        (`T2F_GAIN)
    ) dut (
        .clk   (clk),
        .rstn  (rstn),
        .t2f_in(t2f_in),
        .scl   (scl),
        .sda   (sda),
        .os_int(os_int)
    );

    // ---- I2C master ----
    i2c_master_model #(.SCL_HALF(25)) master (.scl(scl), .sda(sda), .clk(clk));

    // ---- T2F behavioral front-end (params from ngspice characterization,
    //      generated by scripts/gen_t2f_model.py) ----
    t2f_model #(
        .CLK_HZ (10.0e6)
    ) u_t2f (
        .clk      (clk),
        .rstn     (rstn),
        .temp_x100(temp_x100),
        .t2f      (t2f_in)
    );

    integer errors = 0;
    reg [255:0] rd;
    reg [7:0] msb, lsb;
    integer half;       // reported temperature in 0.5 C units
    integer exp_half;

    task check_temp;
        input signed [31:0] t_set;  // 0.01 C units
        input integer exp;          // expected 0.5 C units
        integer want;
        begin
            temp_x100 = t_set;
            // wait for the gate window + settle (GATE_CYCLES/10MHz = 10 ms)
            #40_000_000;
            // manual edge count over the last 10ms
            begin : dbgblk
                integer ec;
                reg t2f_d2;
                ec = 0; t2f_d2 = 0;
                repeat (100000) @(posedge clk) begin
                    if (t2f_in && !t2f_d2) ec = ec + 1;
                    t2f_d2 = t2f_in;
                end
            end
            master.i2c_read_regs(7'h48, 8'h00, 2, rd);
            msb = rd[7:0];
            lsb = rd[15:8];
            half = {msb, lsb[7]};       // 9-bit two's complement
            if (half >= 256) half = half - 512;
            want = exp;
            if (half == want) begin
                $display("PASS T=%0d.%02dC  temp=0x%02x_%02x (%0d half-steps)",
                         t_set/100, t_set%100, msb, lsb, half);
            end else begin
                errors = errors + 1;
                $display("FAIL T=%0d.%02dC  got %0d half-steps (%02x_%02x), exp %0d",
                         t_set/100, t_set%100, half, msb, lsb, want);
            end
        end
    endtask

    initial begin
        $dumpfile("tb_top.vcd");
        $dumpvars(0, tb_top);
        repeat (5) @(posedge clk);
        rstn = 1;
        repeat (10) @(posedge clk);

        // 25 C  -> 50 half-steps (0.5 C units)
        check_temp(2500, 50);
        // -40 C -> -80 half-steps -> 9-bit two's complement = 432 (0x1B0)
        check_temp(-4000, -80);
        // 125 C -> 250 half-steps
        check_temp(12500, 250);
        // alert check: with default TOS=100C, at 125C os_int should assert
        if (os_int === 1'b0)
            $display("PASS os_int asserted at 125C");
        else begin
            errors = errors + 1;
            $display("FAIL os_int not asserted at 125C");
        end

        // 0 C -> 0 half-steps
        check_temp(0, 0);


        if (errors == 0)
            $display("== ALL TOP-LEVEL TESTS PASSED ==");
        else
            $display("== %0d TOP-LEVEL TEST(S) FAILED ==", errors);
        $finish;
    end

endmodule
